import { setup } from "@contentful/dam-app-base";
import { render } from "react-dom";
import logo from "./logo.png";
import "./index.css";
import { InstantSearch } from "./InstantSearch";

const CTA = "Select DAM media";

setup({
  cta: CTA,
  name: "Acquia DAM App",
  logo,
  color: "#036FE3",
  description:
    "Acquia DAM app provides integration between Contentful and Acquia DAM.",
  parameterDefinitions: [
    {
      id: "domain",
      type: "Symbol",
      name: "Acquia DAM Domain",
      description: "Provide the domain name here",
      required: true,
    },
    {
      id: "authToken",
      type: "Symbol",
      name: "Auth Token",
      description: (
        <span>
          A personal access token can be generated by logging into the Acquia
          DAM application and accessing the API Setup page (Admin | Global
          Settings). Read more{" "}
          <a
            target="_blank"
            href="https://widenv2.docs.apiary.io/#introduction/authentication"
          >
            here
          </a>
        </span>
      ),
      required: true,
    },
  ],
  validateParameters,
  makeThumbnail,
  renderDialog,
  openDialog,
  isDisabled: () => false,
});

function makeThumbnail(attachment) {
  const thumbnail = attachment.thumbnail_link;
  const url = typeof thumbnail === "string" ? thumbnail : undefined;
  const alt = attachment.embed_name;
  return [url, alt];
}

async function renderDialog(sdk) {
  render(<InstantSearch sdk={sdk} />, document.getElementById("root"));
  sdk.window.startAutoResizer();
}

async function openDialog(sdk, _currentValue, _config) {
  const result = await sdk.dialogs.openCurrentApp({
    position: "center",
    title: CTA,
    shouldCloseOnOverlayClick: true,
    shouldCloseOnEscapePress: true,
    width: 1200,
    minHeight: 800,
    allowHeightOverflow: true,
  });

  if (!Array.isArray(result)) {
    return [];
  }

  return result.map((asset) => asset);
}

function validateParameters({ authToken, domain }) {
  if (!domain) {
    return "Please add Acquia DAM Domain";
  }

  if (!authToken) {
    return "Please add an auth token";
  }

  return null;
}
